#ifndef __FEATURE_MACROS_INC
#define __FEATURE_MACROS_INC

#pragma shader_feature_local _ _BASECOLOR_MAP
#pragma shader_feature_local _ _NORMAL_MAP
#pragma shader_feature_local _ _METALLIC_MAP
#pragma shader_feature_local _ _ROUGHNESS_MAP
#pragma shader_feature_local _ _CUBEMAP
#pragma shader_feature_local _ _EMISSION
#pragma shader_feature_local _ _RENDERING_CUTOUT
#pragma shader_feature_local _ _RENDERING_CUTOUT_STOCHASTIC
#pragma shader_feature_local _ _RENDERING_FADE
#pragma shader_feature_local _ _RENDERING_TRANSPARENT
#pragma shader_feature_local _ _RENDERING_TRANSCLIPPING
#pragma shader_feature_local _ _OUTLINES
#pragma shader_feature_local _ _GLITTER
#pragma shader_feature_local _ _EXPLODE
#pragma shader_feature_local _ _SCROLL
#pragma shader_feature_local _ _UVSCROLL
#pragma shader_feature_local _ _MATCAP0
#pragma shader_feature_local _ _MATCAP0_MASK
#pragma shader_feature_local _ _MATCAP0_MASK2
#pragma shader_feature_local _ _MATCAP1
#pragma shader_feature_local _ _MATCAP1_MASK
#pragma shader_feature_local _ _MATCAP1_MASK2
#pragma shader_feature_local _ _RIM_LIGHTING0
#pragma shader_feature_local _ _RIM_LIGHTING0_MASK
#pragma shader_feature_local _ _RIM_LIGHTING0_GLITTER
#pragma shader_feature_local _ _RIM_LIGHTING0_POLAR_MASK
#pragma shader_feature_local _ _RIM_LIGHTING1
#pragma shader_feature_local _ _RIM_LIGHTING1_MASK
#pragma shader_feature_local _ _RIM_LIGHTING1_GLITTER
#pragma shader_feature_local _ _RIM_LIGHTING1_POLAR_MASK
#pragma shader_feature_local _ _OKLAB
#pragma shader_feature_local _ _CLONES
#pragma shader_feature_local _ _PBR_OVERLAY0
#pragma shader_feature_local _ _PBR_OVERLAY0_BASECOLOR_MAP
#pragma shader_feature_local _ _PBR_OVERLAY0_EMISSION_MAP
#pragma shader_feature_local _ _PBR_OVERLAY0_NORMAL_MAP
#pragma shader_feature_local _ _PBR_OVERLAY0_ROUGHNESS_MAP
#pragma shader_feature_local _ _PBR_OVERLAY0_METALLIC_MAP
#pragma shader_feature_local _ _PBR_OVERLAY0_MASK
#pragma shader_feature_local _ _PBR_OVERLAY0_MIX_ALPHA_BLEND
#pragma shader_feature_local _ _PBR_OVERLAY0_MIX_ADD
#pragma shader_feature_local _ _PBR_OVERLAY0_MIX_MIN
#pragma shader_feature_local _ _PBR_OVERLAY0_MIX_MAX
#pragma shader_feature_local _ _PBR_OVERLAY1
#pragma shader_feature_local _ _PBR_OVERLAY1_BASECOLOR_MAP
#pragma shader_feature_local _ _PBR_OVERLAY1_EMISSION_MAP
#pragma shader_feature_local _ _PBR_OVERLAY1_NORMAL_MAP
#pragma shader_feature_local _ _PBR_OVERLAY1_ROUGHNESS_MAP
#pragma shader_feature_local _ _PBR_OVERLAY1_METALLIC_MAP
#pragma shader_feature_local _ _PBR_OVERLAY1_MASK
#pragma shader_feature_local _ _PBR_OVERLAY1_MIX_ALPHA_BLEND
#pragma shader_feature_local _ _PBR_OVERLAY1_MIX_ADD
#pragma shader_feature_local _ _PBR_OVERLAY1_MIX_MIN
#pragma shader_feature_local _ _PBR_OVERLAY1_MIX_MAX
#pragma shader_feature_local _ _PBR_OVERLAY2
#pragma shader_feature_local _ _PBR_OVERLAY2_BASECOLOR_MAP
#pragma shader_feature_local _ _PBR_OVERLAY2_EMISSION_MAP
#pragma shader_feature_local _ _PBR_OVERLAY2_NORMAL_MAP
#pragma shader_feature_local _ _PBR_OVERLAY2_ROUGHNESS_MAP
#pragma shader_feature_local _ _PBR_OVERLAY2_METALLIC_MAP
#pragma shader_feature_local _ _PBR_OVERLAY2_MASK
#pragma shader_feature_local _ _PBR_OVERLAY2_MIX_ALPHA_BLEND
#pragma shader_feature_local _ _PBR_OVERLAY2_MIX_ADD
#pragma shader_feature_local _ _PBR_OVERLAY2_MIX_MIN
#pragma shader_feature_local _ _PBR_OVERLAY2_MIX_MAX
#pragma shader_feature_local _ _PBR_OVERLAY3
#pragma shader_feature_local _ _PBR_OVERLAY3_BASECOLOR_MAP
#pragma shader_feature_local _ _PBR_OVERLAY3_EMISSION_MAP
#pragma shader_feature_local _ _PBR_OVERLAY3_NORMAL_MAP
#pragma shader_feature_local _ _PBR_OVERLAY3_ROUGHNESS_MAP
#pragma shader_feature_local _ _PBR_OVERLAY3_METALLIC_MAP
#pragma shader_feature_local _ _PBR_OVERLAY3_MASK
#pragma shader_feature_local _ _PBR_OVERLAY3_MIX_ALPHA_BLEND
#pragma shader_feature_local _ _PBR_OVERLAY3_MIX_ADD
#pragma shader_feature_local _ _PBR_OVERLAY3_MIX_MIN
#pragma shader_feature_local _ _PBR_OVERLAY3_MIX_MAX
#pragma shader_feature_local _ _DECAL0
#pragma shader_feature_local _ _DECAL1
#pragma shader_feature_local _ _DECAL2
#pragma shader_feature_local _ _DECAL3
#pragma shader_feature_local _ _LTCGI
#pragma shader_feature_local _ _TESSELLATION
#pragma shader_feature_local _ _MATCAP0_DISTORTION0
#pragma shader_feature_local _ _MATCAP1_DISTORTION0
#pragma shader_feature_local _ _AMBIENT_OCCLUSION
#pragma shader_feature_local _ _GIMMICK_FLAT_COLOR
#pragma shader_feature_local _ _GIMMICK_QUANTIZE_LOCATION
#pragma shader_feature_local _ _GIMMICK_QUANTIZE_LOCATION_AUDIOLINK
#pragma shader_feature_local _ _GIMMICK_SHEAR_LOCATION
#pragma shader_feature_local _ _GIMMICK_SPHERIZE_LOCATION
#pragma shader_feature_local _ _GIMMICK_EYES_00
#pragma shader_feature_local _ _PIXELLATE
#pragma shader_feature_local _ _TROCHOID
#pragma shader_feature_local _ _CLEARCOAT

#endif  // __FEATURE_MACROS_INC

